# =============================================================================
# Ansible Inventory - Auto-generated by Terraform
# =============================================================================
# Environment: ${environment}
# Generated: Auto-generated - Do not edit manually
# =============================================================================

[app_servers]
${environment}-app ansible_host=${app_server_ip} instance_id=${app_server_id}

[app_servers:vars]
ansible_user=${ssh_user}
ansible_ssh_private_key_file=${ssh_key_path}
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[${environment}:children]
app_servers

[all:vars]
environment=${environment}
