# =============================================================================
# Ansible Inventory - Production Environment
# =============================================================================
# Current Production Server
# =============================================================================

[app_servers]
production-app ansible_host=13.48.13.155

[app_servers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/Downloads/EMSkey.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[production:children]
app_servers

[all:vars]
environment=production
